### ISSUE TITLE
non-zero code: 2

### ISSUE THREAD

**Issue by iamdexterpark** [iwaseyusuke/docker-gobgp-alpine#1]
When I attempt to build this from just the docker container I receive the following exit code:

OK: 145 MiB in 38 packages
# github.com/osrg/gobgp/packet/bgp
/go/src/github.com/osrg/gobgp/packet/bgp/bgp.go:4093: undefined: sort.SliceStable
/go/src/github.com/osrg/gobgp/packet/bgp/bgp.go:4314: undefined: sort.SliceStable
/go/src/github.com/osrg/gobgp/packet/bgp/bgp.go:4332: undefined: sort.SliceStable
/go/src/github.com/osrg/gobgp/packet/bgp/bgp.go:4351: undefined: sort.SliceStable
/go/src/github.com/osrg/gobgp/packet/bgp/bgp.go:4369: undefined: sort.SliceStable
/go/src/github.com/osrg/gobgp/packet/bgp/bgp.go:4388: undefined: sort.SliceStable
The command '/bin/sh -c apk add --no-cache --virtual=build-dependencies     gcc     git     linux-headers     musl-dev  && apk add --no-cache     vim  && rm /usr/bin/vi && ln -s /usr/bin/vim /usr/bin/vi  && go get github.com/osrg/gobgp/gobgp  && go get github.com/osrg/gobgp/gobgpd  && rm -rf ${GOPATH}/pkg/* ${GOPATH}/src/*  && apk del --purge build-dependencies' returned a non-zero code: 2

**Comment by iwaseyusuke** [comment]
Thanks a lot for your reporting!
This should be fixed in the latest master.
